---
version: 2
snapshots:
- name: "mod2"
  columns:
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "dbt_valid_to"
    dataType:
      type: "Double"
  - name: "dbt_updated_at"
    dataType:
      type: "Double"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "p_int"
    dataType:
      type: "Integer"
  - name: "c_double"
    dataType:
      type: "Double"
  - name: "c_map"
    dataType:
      type: "Map"
      keyType:
        type: "String"
      valueType:
        type: "Integer"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
      - name: "start_date"
        dataType:
          type: "Date"
      - name: "is_available"
        dataType:
          type: "Boolean"
      - name: "yearlyrates"
        dataType:
          type: "Array"
          dataType:
            type: "Integer"
      - name: "roomsizes"
        dataType:
          type: "Struct"
          fields:
          - name: "r_name"
            dataType:
              type: "String"
          - name: "size"
            dataType:
              type: "Integer"
  - name: "c_decimal"
    dataType:
      type: "Decimal"
  - name: "c_date"
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "Double"
  - name: "c_array_struct"
    dataType:
      type: "Array"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
        - name: "start_date"
          dataType:
            type: "Date"
        - name: "is_available"
          dataType:
            type: "Boolean"
        - name: "yearlyrates"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
        - name: "roomsizes"
          dataType:
            type: "Struct"
            fields:
            - name: "r_name"
              dataType:
                type: "String"
            - name: "size"
              dataType:
                type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_timestamp"
    dataType:
      type: "Timestamp"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  - name: "c_binary"
    dataType:
      type: "Binary"
  - name: "p_string"
    dataType:
      type: "String"
  tests: []
- name: "mod4"
  columns:
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "dbt_valid_to"
    dataType:
      type: "Float"
  - name: "dbt_updated_at"
    dataType:
      type: "Float"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "p_int"
    dataType:
      type: "Integer"
  - name: "c_double"
    dataType:
      type: "Double"
  - name: "c_map"
    dataType:
      type: "Map"
      keyType:
        type: "String"
      valueType:
        type: "Integer"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
      - name: "start_date"
        dataType:
          type: "Date"
      - name: "is_available"
        dataType:
          type: "Boolean"
      - name: "yearlyrates"
        dataType:
          type: "Array"
          dataType:
            type: "Integer"
      - name: "roomsizes"
        dataType:
          type: "Struct"
          fields:
          - name: "r_name"
            dataType:
              type: "String"
          - name: "size"
            dataType:
              type: "Integer"
  - name: "c_decimal"
    dataType:
      type: "Decimal"
  - name: "c_date"
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "Float"
  - name: "c_array_struct"
    dataType:
      type: "Array"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
        - name: "start_date"
          dataType:
            type: "Date"
        - name: "is_available"
          dataType:
            type: "Boolean"
        - name: "yearlyrates"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
        - name: "roomsizes"
          dataType:
            type: "Struct"
            fields:
            - name: "r_name"
              dataType:
                type: "String"
            - name: "size"
              dataType:
                type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_timestamp"
    dataType:
      type: "Timestamp"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  - name: "c_binary"
    dataType:
      type: "Binary"
  - name: "p_string"
    dataType:
      type: "String"
  tests: []
- name: "mod5"
  columns:
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "dbt_valid_to"
    dataType:
      type: "SmallInt"
  - name: "dbt_updated_at"
    dataType:
      type: "SmallInt"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "p_int"
    dataType:
      type: "Integer"
  - name: "c_double"
    dataType:
      type: "Double"
  - name: "c_map"
    dataType:
      type: "Map"
      keyType:
        type: "String"
      valueType:
        type: "Integer"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
      - name: "start_date"
        dataType:
          type: "Date"
      - name: "is_available"
        dataType:
          type: "Boolean"
      - name: "yearlyrates"
        dataType:
          type: "Array"
          dataType:
            type: "Integer"
      - name: "roomsizes"
        dataType:
          type: "Struct"
          fields:
          - name: "r_name"
            dataType:
              type: "String"
          - name: "size"
            dataType:
              type: "Integer"
  - name: "c_decimal"
    dataType:
      type: "Decimal"
  - name: "c_date"
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "SmallInt"
  - name: "c_array_struct"
    dataType:
      type: "Array"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
        - name: "start_date"
          dataType:
            type: "Date"
        - name: "is_available"
          dataType:
            type: "Boolean"
        - name: "yearlyrates"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
        - name: "roomsizes"
          dataType:
            type: "Struct"
            fields:
            - name: "r_name"
              dataType:
                type: "String"
            - name: "size"
              dataType:
                type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_timestamp"
    dataType:
      type: "Timestamp"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  - name: "c_binary"
    dataType:
      type: "Binary"
  - name: "p_string"
    dataType:
      type: "String"
  tests: []
- name: "mod6"
  columns:
  - name: "c_float"
    dataType:
      type: "Float"
  - name: "dbt_valid_to"
    dataType:
      type: "Float"
  - name: "dbt_updated_at"
    dataType:
      type: "Float"
  - name: "c_boolean"
    dataType:
      type: "Boolean"
  - name: "c_smallint"
    dataType:
      type: "SmallInt"
  - name: "c_array"
    dataType:
      type: "Array"
      dataType:
        type: "String"
  - name: "p_int"
    dataType:
      type: "Integer"
  - name: "c_double"
    dataType:
      type: "Double"
  - name: "c_map"
    dataType:
      type: "Map"
      keyType:
        type: "String"
      valueType:
        type: "Integer"
  - name: "c_struct"
    dataType:
      type: "Struct"
      fields:
      - name: "city"
        dataType:
          type: "String"
      - name: "state"
        dataType:
          type: "String"
      - name: "pin"
        dataType:
          type: "Bigint"
      - name: "start_date"
        dataType:
          type: "Date"
      - name: "is_available"
        dataType:
          type: "Boolean"
      - name: "yearlyrates"
        dataType:
          type: "Array"
          dataType:
            type: "Integer"
      - name: "roomsizes"
        dataType:
          type: "Struct"
          fields:
          - name: "r_name"
            dataType:
              type: "String"
          - name: "size"
            dataType:
              type: "Integer"
  - name: "c_decimal"
    dataType:
      type: "Decimal"
  - name: "c_date"
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "Float"
  - name: "c_array_struct"
    dataType:
      type: "Array"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
        - name: "start_date"
          dataType:
            type: "Date"
        - name: "is_available"
          dataType:
            type: "Boolean"
        - name: "yearlyrates"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
        - name: "roomsizes"
          dataType:
            type: "Struct"
            fields:
            - name: "r_name"
              dataType:
                type: "String"
            - name: "size"
              dataType:
                type: "Integer"
  - name: "c_bigint"
    dataType:
      type: "Bigint"
  - name: "c_timestamp"
    dataType:
      type: "Timestamp"
  - name: "c_int"
    dataType:
      type: "Integer"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  - name: "c_string"
    dataType:
      type: "String"
  - name: "c_tinyint"
    dataType:
      type: "TinyInt"
  - name: "c_binary"
    dataType:
      type: "Binary"
  - name: "p_string"
    dataType:
      type: "String"
  tests: []
